deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: tsdb
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: s3
      schema: v13
  storage_config:
    tsdb_shipper:
      cache_ttl: 24h
      #shared_store: s3
    aws:
      s3: "http://minioadmin:minioadmin@loki.minio-dev.svc.cluster.local.:9000"
      s3forcepathstyle: true
      bucketnames: "loki"
      #region: "eu-north-1"
      # access_key_id: E8XW66gYMagRe2QHssnt
      # secret_access_key: VBj4HtFs8sVY5Utwamyh0lOsV7MSSZzGA2MU0YXT
singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
